// frontend/src/components/views/Home.jsx
import React from 'react';
import styled from 'styled-components';
import { Grid, OutlinedInput } from '@material-ui/core';


const home = require('assets/home.png');

const FlexGrid = styled(Grid)`
  background-position: center center;
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: cover;
  background-image: url(${home});
  height: 90vh;
`;

const Input = styled(OutlinedInput)`
  width: 60%;
  align-self: center;
  background-color: #fff;
  border-radius: 60;
`;

const Title = styled.p`
  text-align: center;
  font-size: 3em;
  font-weight: bold;
  color: #255219;
  justify-content: center;
  align-self: center;
`;

const Home = () => (
  <FlexGrid container direction="column" justify="center" align="center">
    <Title>
      Débarrassez vous de vos allergies alimentaires !
      <span role="img" aria-label="smile">
        😁
      </span>
    </Title>
    <Input placeholder="Un aliment? " />
  </FlexGrid>
);

export default Home;

// vueapp/src/views/Home.vue
<template>
  <div class="hero-body">
    <div class="container has-text-centered">
      <div class="frame">
        <p class="title">Débarrassez-vous de vos allergies alimentaires !</p>
        <p class="subtitle">Ou trouvez simplement un moyen de mieux manger ! 😁</p>
        <div class="column is-three-fifths is-offset-one-fifth">
          <input
            class="input is-large is-rounded"
            type="text"
            placeholder="Chercher un aliment... "
          >
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {}
</script>


<style type="text/css" scoped>
.title {
  font-size: 75px;
  color: #255219;
  font-weight: bolder;
  z-index: 12456789098765432;
}

.subtitle {
  font-size: 30px;
  font-weight: bold;
  opacity: 2;
  color: #255219;
}

.hero-body {
  background-image: url('../assets/img/home.png');
  background-position: center center;
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: cover;
}
</style>
